---
title: "Introduction to cryptor"
author: "Thibaut Van Weehaeghe"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to cryptor}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Overview

cryptor provides a generalized API wrapper for multiple data sources:

1. Kraken
2. Binance
3. Nomics

```{r init}
library(cryptor)
```

# Kraken

The original Kraken API documentation can be found [here](https://www.kraken.com/help/api).

```{r kraken.public}
kraken_servertime()
kraken_assets()
kraken_assetpairs(excl_darkpool = TRUE)
kraken_assetpairs(excl_darkpool = FALSE)
kraken_candles(pairs = "XBTEUR", interval = 1440)
kraken_candles(pairs = c("BCHEUR", "XBTEUR"), interval = 1440)
kraken_candles(pairs = "ETHEUR", interval = 240)
kraken_lastprice(pair = "EOSEUR")
kraken_orderbook(pair = "XBTEUR", count = 5)
kraken_spread(pair = "XBTEUR")
```

```{r kraken.private}

```

# Nomics

The original Nomics API documentation can be found [here](http://docs.nomics.com/).

```{r cred.nomics}
credentials_nomics(key = "2018-09-demo-dont-deploy-b69315e440beb145") # demo API key can be outdated
```

```{r}
nomics_markets()
nomics_markets(exchange = 'kraken')
nomics_markets(exchange = 'kraken', base = 'btc', quote = 'eur')

nomics_currencies()

nomics_prices()
nomics_prices_markets()
nomics_prices_markets(currency = 'btc')
nomics_prices_markets(currency = 'eth')
nomics_prices_markets(currency = 'abc')


nomics_prices_exchange_markets()
nomics_prices_exchange_markets(currency = 'btc')
nomics_prices_exchange_markets(currency = 'btc',exchange = 'kraken')


nomics_candles_aggr()
nomics_candles_aggr(interval = '1d')
nomics_candles_aggr(interval = '1d', currency = 'eth')
nomics_candles_aggr(interval = '1d', currency = 'xlm', start = lubridate::ymd(20180101))
nomics_candles_aggr(interval = '1h', currency = 'bch', start = lubridate::ymd(20180101))

nomics_candles(exchange = 'kraken', market = 'xxbtzeur')
nomics_candles(exchange = 'kraken', market = 'xxbtzeur', interval = '1h')
```

